/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package users;
import admin.Admin_TicketBooking;
import javaProject.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaProject.DB_Connectivity;
import javaProject.LogIn;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class TicketBooking extends javax.swing.JFrame {
ResultSet rs;
    public TicketBooking() {
        initComponents();
         DB_Connectivity db = new DB_Connectivity();
        
        nameTextField.setEditable(false);
        cnicTextField.setEditable(false);
        sourceField.setEditable(false);
        destinationField.setEditable(false);
        arrivalField.setEditable(false);
        flightDayField.setEditable(false);
        ticketPriceField.setEditable(false);
       
         
         rs=db.RetrieveFlightNoFromFlights();
        try {
            while (rs.next()) {
                String value1 = rs.getString(1);
                flightNoComboBox.addItem(value1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FlightTimings.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        rs=db.RetrievePassengerIDFromPassenger();
        try {
            while (rs.next()) {
                String value1 = rs.getString(1);
                passengerIDComboBox.addItem(value1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FlightTimings.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        try {
            rs=db.TicketNo();
            rs.next();
            if (rs.getString("MAX(ticket_no)") == null) {
                    tktno.setText("TKT-001");         
                }else{
                    long ticketNo = Long.parseLong(rs.getString("MAX(ticket_no)").substring(4,rs.getString("MAX(ticket_no)").length()));
                    ticketNo++;
                    tktno.setText("TKT-" + String.format("%03d", ticketNo));
            }
    } catch (SQLException ex) {
        Logger.getLogger(TicketBooking.class.getName()).log(Level.SEVERE, null, ex);
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleBarPanel = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        projectTitleLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        SideBarPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        ticketBookingPanel = new javax.swing.JPanel();
        TicketBooking = new javax.swing.JLabel();
        flightTimingsPanel = new javax.swing.JPanel();
        flightTimings = new javax.swing.JLabel();
        ticketPricesPanel = new javax.swing.JPanel();
        ticketPrices = new javax.swing.JLabel();
        LogoutPanel = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        detailsLabel = new javax.swing.JLabel();
        sidebarIconLabel = new javax.swing.JLabel();
        passengerPanel = new javax.swing.JPanel();
        passengerDetails = new javax.swing.JLabel();
        dashboardPanel = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        sourceLabel = new javax.swing.JLabel();
        classLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        destinationLabel = new javax.swing.JLabel();
        ticketBookingLabel = new javax.swing.JLabel();
        FlightIcon = new javax.swing.JLabel();
        flightDayLabel = new javax.swing.JLabel();
        flightDetailsLabel = new javax.swing.JLabel();
        ticketBookButton = new javax.swing.JButton();
        ticketPriceLabel = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        flightDayField = new javax.swing.JTextField();
        ticketPriceField = new javax.swing.JTextField();
        destinationField = new javax.swing.JTextField();
        sourceField = new javax.swing.JTextField();
        flightNoComboBox = new javax.swing.JComboBox<>();
        flightDetailsLabel1 = new javax.swing.JLabel();
        passengerIDComboBox = new javax.swing.JComboBox<>();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        cnicLabel = new javax.swing.JLabel();
        cnicTextField = new javax.swing.JTextField();
        departureLabel = new javax.swing.JLabel();
        departureField = new javax.swing.JTextField();
        arrivalLabel = new javax.swing.JLabel();
        arrivalField = new javax.swing.JTextField();
        flightClassComboBox = new javax.swing.JComboBox<>();
        tktno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleBarPanel.setBackground(new java.awt.Color(102, 102, 255));
        TitleBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setBackground(new java.awt.Color(255, 255, 255));
        closeLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 28)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLabel.setText("X");
        closeLabel.setToolTipText("");
        closeLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        TitleBarPanel.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 20, 50, 50));

        projectTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        projectTitleLabel.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        projectTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        projectTitleLabel.setText("AIRLINE TICKET BOOKING SYSTEM");
        TitleBarPanel.add(projectTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 15, 970, -1));

        welcomeLabel.setBackground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/User_Icon.png"))); // NOI18N
        welcomeLabel.setText("Welcome");
        TitleBarPanel.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 20, -1, -1));

        getContentPane().add(TitleBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 1540, 90));

        SideBarPanel.setBackground(new java.awt.Color(51, 51, 51));
        SideBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePanel.setBackground(new java.awt.Color(51, 51, 51));
        homePanel.setForeground(new java.awt.Color(255, 255, 255));
        homePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePanelMouseClicked(evt);
            }
        });

        home.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Home_Icon.png"))); // NOI18N
        home.setText("  Home");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(home)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 380, 80));

        ticketBookingPanel.setBackground(new java.awt.Color(255, 51, 51));
        ticketBookingPanel.setForeground(new java.awt.Color(255, 255, 255));

        TicketBooking.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        TicketBooking.setForeground(new java.awt.Color(255, 255, 255));
        TicketBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Ticket_Icon.png"))); // NOI18N
        TicketBooking.setText("  Ticket Booking");

        javax.swing.GroupLayout ticketBookingPanelLayout = new javax.swing.GroupLayout(ticketBookingPanel);
        ticketBookingPanel.setLayout(ticketBookingPanelLayout);
        ticketBookingPanelLayout.setHorizontalGroup(
            ticketBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketBookingPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(TicketBooking)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        ticketBookingPanelLayout.setVerticalGroup(
            ticketBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketBookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TicketBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel.add(ticketBookingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 380, 80));

        flightTimingsPanel.setBackground(new java.awt.Color(51, 51, 51));
        flightTimingsPanel.setForeground(new java.awt.Color(255, 255, 255));
        flightTimingsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flightTimingsPanelMouseClicked(evt);
            }
        });

        flightTimings.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        flightTimings.setForeground(new java.awt.Color(255, 255, 255));
        flightTimings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Flight_Timing_Icon.png"))); // NOI18N
        flightTimings.setText("  Flight Timings");

        javax.swing.GroupLayout flightTimingsPanelLayout = new javax.swing.GroupLayout(flightTimingsPanel);
        flightTimingsPanel.setLayout(flightTimingsPanelLayout);
        flightTimingsPanelLayout.setHorizontalGroup(
            flightTimingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightTimingsPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(flightTimings)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        flightTimingsPanelLayout.setVerticalGroup(
            flightTimingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightTimingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flightTimings, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel.add(flightTimingsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 380, 80));

        ticketPricesPanel.setBackground(new java.awt.Color(51, 51, 51));
        ticketPricesPanel.setForeground(new java.awt.Color(255, 255, 255));
        ticketPricesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketPricesPanelMouseClicked(evt);
            }
        });

        ticketPrices.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        ticketPrices.setForeground(new java.awt.Color(255, 255, 255));
        ticketPrices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Ticket_Price_Icon.png"))); // NOI18N
        ticketPrices.setText("Ticket Prices");

        javax.swing.GroupLayout ticketPricesPanelLayout = new javax.swing.GroupLayout(ticketPricesPanel);
        ticketPricesPanel.setLayout(ticketPricesPanelLayout);
        ticketPricesPanelLayout.setHorizontalGroup(
            ticketPricesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketPricesPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(ticketPrices)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        ticketPricesPanelLayout.setVerticalGroup(
            ticketPricesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketPricesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketPrices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel.add(ticketPricesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 380, 80));

        LogoutPanel.setBackground(new java.awt.Color(51, 51, 51));
        LogoutPanel.setForeground(new java.awt.Color(255, 255, 255));
        LogoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Logout_Exit_Icon.png"))); // NOI18N
        logout.setText("  Logout");

        javax.swing.GroupLayout LogoutPanelLayout = new javax.swing.GroupLayout(LogoutPanel);
        LogoutPanel.setLayout(LogoutPanelLayout);
        LogoutPanelLayout.setHorizontalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(logout)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        LogoutPanelLayout.setVerticalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel.add(LogoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 380, 80));

        detailsLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        detailsLabel.setForeground(new java.awt.Color(204, 204, 204));
        detailsLabel.setText("Details");
        SideBarPanel.add(detailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, 20));

        sidebarIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Menu_Icon.png"))); // NOI18N
        SideBarPanel.add(sidebarIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        passengerPanel.setBackground(new java.awt.Color(51, 51, 51));
        passengerPanel.setForeground(new java.awt.Color(255, 255, 255));
        passengerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passengerPanelMouseClicked(evt);
            }
        });

        passengerDetails.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        passengerDetails.setForeground(new java.awt.Color(255, 255, 255));
        passengerDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Passenger_Icon.png"))); // NOI18N
        passengerDetails.setText("  Passenger");

        javax.swing.GroupLayout passengerPanelLayout = new javax.swing.GroupLayout(passengerPanel);
        passengerPanel.setLayout(passengerPanelLayout);
        passengerPanelLayout.setHorizontalGroup(
            passengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passengerPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(passengerDetails)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        passengerPanelLayout.setVerticalGroup(
            passengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passengerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passengerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel.add(passengerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 380, 80));

        getContentPane().add(SideBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 1080));

        dashboardPanel.setBackground(new java.awt.Color(255, 255, 255));

        dateLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(51, 51, 51));
        dateLabel.setText("Flight Class :");

        sourceLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        sourceLabel.setForeground(new java.awt.Color(51, 51, 51));
        sourceLabel.setText("Source :");

        classLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        classLabel.setForeground(new java.awt.Color(51, 51, 51));
        classLabel.setText("Flight Date :");

        backButton.setBackground(new java.awt.Color(51, 51, 51));
        backButton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        destinationLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        destinationLabel.setForeground(new java.awt.Color(51, 51, 51));
        destinationLabel.setText("Destination :");

        ticketBookingLabel.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        ticketBookingLabel.setForeground(new java.awt.Color(255, 51, 51));
        ticketBookingLabel.setText("TICKET BOOKING");

        FlightIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Ticket_Booking_Img.png"))); // NOI18N

        flightDayLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        flightDayLabel.setForeground(new java.awt.Color(51, 51, 51));
        flightDayLabel.setText("Flight Day :");

        flightDetailsLabel.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        flightDetailsLabel.setForeground(new java.awt.Color(51, 51, 51));
        flightDetailsLabel.setText("Flight No :");

        ticketBookButton.setBackground(new java.awt.Color(51, 51, 51));
        ticketBookButton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        ticketBookButton.setForeground(new java.awt.Color(255, 255, 255));
        ticketBookButton.setText("Book");
        ticketBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketBookButtonActionPerformed(evt);
            }
        });

        ticketPriceLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        ticketPriceLabel.setForeground(new java.awt.Color(51, 51, 51));
        ticketPriceLabel.setText("Ticket Price :");

        dateChooser.setFont(new java.awt.Font("Yu Gothic Medium", 1, 20)); // NOI18N

        flightDayField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N

        ticketPriceField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N

        destinationField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N

        sourceField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N

        flightNoComboBox.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 21)); // NOI18N
        flightNoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Flight Number" }));
        flightNoComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                flightNoComboBoxItemStateChanged(evt);
            }
        });
        flightNoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightNoComboBoxActionPerformed(evt);
            }
        });

        flightDetailsLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        flightDetailsLabel1.setForeground(new java.awt.Color(51, 51, 51));
        flightDetailsLabel1.setText("Passenger ID:");

        passengerIDComboBox.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 21)); // NOI18N
        passengerIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Passenger ID" }));
        passengerIDComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                passengerIDComboBoxItemStateChanged(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(51, 51, 51));
        nameLabel.setText("P_Name :");

        nameTextField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N

        cnicLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        cnicLabel.setForeground(new java.awt.Color(51, 51, 51));
        cnicLabel.setText("P_CNIC :");

        cnicTextField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N

        departureLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        departureLabel.setForeground(new java.awt.Color(51, 51, 51));
        departureLabel.setText("Departure :");

        departureField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N

        arrivalLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        arrivalLabel.setForeground(new java.awt.Color(51, 51, 51));
        arrivalLabel.setText("Arrival :");

        arrivalField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N

        flightClassComboBox.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        flightClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Class", "Economy", "Business" }));
        flightClassComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                flightClassComboBoxItemStateChanged(evt);
            }
        });
        flightClassComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightClassComboBoxActionPerformed(evt);
            }
        });

        tktno.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        tktno.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ticketBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                                        .addComponent(dateLabel)
                                        .addGap(15, 15, 15)
                                        .addComponent(flightClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sourceLabel)
                                            .addComponent(flightDayLabel)
                                            .addComponent(nameLabel)
                                            .addComponent(departureLabel))
                                        .addGap(27, 27, 27)
                                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(flightDayField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sourceField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(departureField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                                        .addGap(169, 169, 169)
                                        .addComponent(ticketPriceLabel))
                                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                                        .addGap(163, 163, 163)
                                        .addComponent(arrivalLabel))))
                            .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addGap(745, 745, 745)
                                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cnicLabel)
                                    .addComponent(flightDetailsLabel)
                                    .addComponent(classLabel)
                                    .addComponent(destinationLabel))))
                        .addGap(18, 18, 18)
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cnicTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addComponent(flightNoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ticketPriceField, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addComponent(destinationField, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(arrivalField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addComponent(flightDetailsLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passengerIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(881, 881, 881))
                            .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addComponent(tktno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FlightIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ticketBookingLabel)
                                .addGap(450, 450, 450))))))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FlightIcon)
                            .addComponent(ticketBookingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                        .addComponent(tktno)
                        .addGap(35, 35, 35)))
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(flightNoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(flightDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passengerIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(flightDetailsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnicLabel)
                    .addComponent(cnicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceLabel)
                    .addComponent(destinationLabel)
                    .addComponent(sourceField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departureLabel)
                    .addComponent(departureField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrivalLabel)
                    .addComponent(arrivalField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(flightDayLabel)
                        .addComponent(flightDayField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(classLabel))
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketPriceLabel)
                    .addComponent(ticketPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel)
                    .addComponent(flightClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketBookButton)
                    .addComponent(backButton))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(dashboardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 1540, 990));

        setSize(new java.awt.Dimension(1920, 1080));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void homePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMouseClicked
        // TODO add your handling code here:
        HomePage obj = new HomePage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_homePanelMouseClicked

    private void ticketPricesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketPricesPanelMouseClicked
        // TODO add your handling code here:
        TicketPrices obj = new TicketPrices();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ticketPricesPanelMouseClicked

    private void LogoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseClicked
        // TODO add your handling code here:
        LogIn obj = new LogIn();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutPanelMouseClicked

    private void passengerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passengerPanelMouseClicked
        // TODO add your handling code here:
        Passenger obj = new Passenger();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_passengerPanelMouseClicked

    private void flightTimingsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flightTimingsPanelMouseClicked
        // TODO add your handling code here:
        FlightTimings obj = new FlightTimings();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_flightTimingsPanelMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();

    }//GEN-LAST:event_backButtonActionPerformed

    private void ticketBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketBookButtonActionPerformed
        // TODO add your handling code here:
        DB_Connectivity db = new DB_Connectivity();//object

        if (db.TicketDetails(tktno.getText(),passengerIDComboBox.getSelectedItem().toString(), flightNoComboBox.getSelectedItem().toString(), nameTextField.getText(), cnicTextField.getText(), sourceField.getText(), destinationField.getText(), departureField.getText(), arrivalField.getText(), flightDayField.getText(), dateChooser.getDate().toLocaleString(), flightClassComboBox.getSelectedItem().toString(), Integer.parseInt(ticketPriceField.getText()) )== 1) {
            JOptionPane.showMessageDialog(this, "Ticket has been Successfully Booking", "Ticket", 1);
            TicketBooking tb = new TicketBooking();
            tb.setVisible(true);
            dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Error", "Registration", 2);
        }

    }//GEN-LAST:event_ticketBookButtonActionPerformed

    private void flightNoComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_flightNoComboBoxItemStateChanged
        // TODO add your handling code here:
        DB_Connectivity db = new DB_Connectivity();
        ResultSet rs = db.DetailsByFlightNo(flightNoComboBox.getSelectedItem().toString());
        try {
            if(rs.next()){
                String source = rs.getString("source");
                String destination = rs.getString("destination");
                String departure = rs.getString("departure");
                String arrival = rs.getString("arrival");
                String day = rs.getString("day");
                // Set the retrieved data in the text fields
                sourceField.setText(source);
                destinationField.setText(destination);
                departureField.setText(departure);
                arrivalField.setText(arrival);
                flightDayField.setText(day);

            }else{
                // If no row is found, clear the text fields
                sourceField.setText("");
                destinationField.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TicketBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_flightNoComboBoxItemStateChanged

    private void flightNoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightNoComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_flightNoComboBoxActionPerformed

    private void passengerIDComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_passengerIDComboBoxItemStateChanged
        // TODO add your handling code here:
        DB_Connectivity db = new DB_Connectivity();
        ResultSet rs = db.DetailsByPassengerId(passengerIDComboBox.getSelectedItem().toString());
        try {
            if(rs.next()){
                String name = rs.getString("name");
                String cnic = rs.getString("cnic");

                // Set the retrieved data in the text fields
                nameTextField.setText(name);
                cnicTextField.setText(cnic);

            }else{
                // If no row is found, clear the text fields
                nameTextField.setText("");
                cnicTextField.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TicketBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_passengerIDComboBoxItemStateChanged

    private void flightClassComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_flightClassComboBoxItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_flightClassComboBoxItemStateChanged

    private void flightClassComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightClassComboBoxActionPerformed
        // TODO add your handling code here:
        DB_Connectivity db = new DB_Connectivity();
        ResultSet rs = db.FlightPriceByClass(flightNoComboBox.getSelectedItem().toString(), flightClassComboBox.getSelectedItem().toString());
        // Execute query to retrieve price
        try {

            if (rs.next()) {
                // Update text field with retrieved price
                ticketPriceField.setText(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TicketBooking.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_flightClassComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FlightIcon;
    private javax.swing.JPanel LogoutPanel;
    private javax.swing.JPanel SideBarPanel;
    private javax.swing.JLabel TicketBooking;
    private javax.swing.JPanel TitleBarPanel;
    private javax.swing.JTextField arrivalField;
    private javax.swing.JLabel arrivalLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel classLabel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel cnicLabel;
    private javax.swing.JTextField cnicTextField;
    private javax.swing.JPanel dashboardPanel;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField departureField;
    private javax.swing.JLabel departureLabel;
    private javax.swing.JTextField destinationField;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JLabel detailsLabel;
    private javax.swing.JComboBox<String> flightClassComboBox;
    private javax.swing.JTextField flightDayField;
    private javax.swing.JLabel flightDayLabel;
    private javax.swing.JLabel flightDetailsLabel;
    private javax.swing.JLabel flightDetailsLabel1;
    private javax.swing.JComboBox<String> flightNoComboBox;
    private javax.swing.JLabel flightTimings;
    private javax.swing.JPanel flightTimingsPanel;
    private javax.swing.JLabel home;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel passengerDetails;
    private javax.swing.JComboBox<String> passengerIDComboBox;
    private javax.swing.JPanel passengerPanel;
    private javax.swing.JLabel projectTitleLabel;
    private javax.swing.JLabel sidebarIconLabel;
    private javax.swing.JTextField sourceField;
    private javax.swing.JLabel sourceLabel;
    private javax.swing.JButton ticketBookButton;
    private javax.swing.JLabel ticketBookingLabel;
    private javax.swing.JPanel ticketBookingPanel;
    private javax.swing.JTextField ticketPriceField;
    private javax.swing.JLabel ticketPriceLabel;
    private javax.swing.JLabel ticketPrices;
    private javax.swing.JPanel ticketPricesPanel;
    private javax.swing.JLabel tktno;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
