/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import users.*;
import javaProject.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class Admin_FlightDetails extends javax.swing.JFrame {
 ResultSet rs;
    public Admin_FlightDetails() {
        try {
            initComponents();
            DB_Connectivity db = new DB_Connectivity();
            rs = db.getFlightDetails();
            DefaultTableModel tb =(DefaultTableModel)flightDetailsTable.getModel();
            
            while(rs.next()){
            String row[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
            tb.addRow(row); 
            }
        }catch (SQLException ex) {
          System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleBarPanel = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        projectTitleLabel = new javax.swing.JLabel();
        adminLabel = new javax.swing.JLabel();
        dashboardPanel = new javax.swing.JPanel();
        passengerDetailsLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        passengerDetailsLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        flightDetailsTable = new rojeru_san.complementos.RSTableMetro();
        SideBarPanel2 = new javax.swing.JPanel();
        Dashboard2 = new javax.swing.JPanel();
        dashbaord = new javax.swing.JLabel();
        passengerDetailsPanel = new javax.swing.JPanel();
        passengerDetails = new javax.swing.JLabel();
        flighDetailstPanel = new javax.swing.JPanel();
        flightDetails = new javax.swing.JLabel();
        ticketBookingPanel = new javax.swing.JPanel();
        ticketBooking = new javax.swing.JLabel();
        ticketCancellationPanel = new javax.swing.JPanel();
        ticketCancellation = new javax.swing.JLabel();
        LogoutPanel = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        sidebarIconLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleBarPanel.setBackground(new java.awt.Color(102, 102, 255));
        TitleBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setBackground(new java.awt.Color(255, 255, 255));
        closeLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 28)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLabel.setText("X");
        closeLabel.setToolTipText("");
        closeLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        TitleBarPanel.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 20, 50, 50));

        projectTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        projectTitleLabel.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        projectTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        projectTitleLabel.setText("AIRLINE TICKET BOOKING SYSTEM");
        TitleBarPanel.add(projectTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 15, 970, -1));

        adminLabel.setBackground(new java.awt.Color(255, 255, 255));
        adminLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        adminLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/User_Icon.png"))); // NOI18N
        adminLabel.setText(" Admin");
        TitleBarPanel.add(adminLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 20, -1, -1));

        getContentPane().add(TitleBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 1540, 90));

        dashboardPanel.setBackground(new java.awt.Color(255, 255, 255));

        passengerDetailsLabel.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        passengerDetailsLabel.setForeground(new java.awt.Color(255, 51, 51));
        passengerDetailsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Ticket_Booking_Img.png"))); // NOI18N

        refreshButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        searchField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 21)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 21)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 21)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 21)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        passengerDetailsLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        passengerDetailsLabel1.setForeground(new java.awt.Color(255, 51, 51));
        passengerDetailsLabel1.setText("FLIGHTS DETAILS");

        flightDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight No", "Source", "Destination", "Departure", "Arrival", "Day", "Economy Price", "Business Price"
            }
        ));
        flightDetailsTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        flightDetailsTable.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        flightDetailsTable.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        flightDetailsTable.setColorSelBackgound(new java.awt.Color(204, 204, 204));
        flightDetailsTable.setColorSelForeground(new java.awt.Color(0, 0, 0));
        flightDetailsTable.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        flightDetailsTable.setFuenteFilas(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        flightDetailsTable.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        flightDetailsTable.setRowHeight(36);
        jScrollPane2.setViewportView(flightDetailsTable);

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addContainerGap(447, Short.MAX_VALUE)
                .addComponent(passengerDetailsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passengerDetailsLabel1)
                .addGap(450, 450, 450))
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refreshButton)
                            .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(dashboardPanelLayout.createSequentialGroup()
                                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(110, 110, 110)
                                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dashboardPanelLayout.createSequentialGroup()
                                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(passengerDetailsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passengerDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(refreshButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(35, 35, 35)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(deleteButton)
                    .addComponent(updateButton))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(dashboardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 1540, 990));

        SideBarPanel2.setBackground(new java.awt.Color(51, 51, 51));
        SideBarPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard2.setBackground(new java.awt.Color(51, 51, 51));
        Dashboard2.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dashboard2MouseClicked(evt);
            }
        });

        dashbaord.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        dashbaord.setForeground(new java.awt.Color(255, 255, 255));
        dashbaord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Home_Icon.png"))); // NOI18N
        dashbaord.setText("  Dashboard");

        javax.swing.GroupLayout Dashboard2Layout = new javax.swing.GroupLayout(Dashboard2);
        Dashboard2.setLayout(Dashboard2Layout);
        Dashboard2Layout.setHorizontalGroup(
            Dashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dashboard2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(dashbaord)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        Dashboard2Layout.setVerticalGroup(
            Dashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dashboard2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashbaord, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel2.add(Dashboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 380, 80));

        passengerDetailsPanel.setBackground(new java.awt.Color(51, 51, 51));
        passengerDetailsPanel.setForeground(new java.awt.Color(255, 255, 255));
        passengerDetailsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passengerDetailsPanelMouseClicked(evt);
            }
        });

        passengerDetails.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        passengerDetails.setForeground(new java.awt.Color(255, 255, 255));
        passengerDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Passenger_Icon.png"))); // NOI18N
        passengerDetails.setText("  Passenger Details");

        javax.swing.GroupLayout passengerDetailsPanelLayout = new javax.swing.GroupLayout(passengerDetailsPanel);
        passengerDetailsPanel.setLayout(passengerDetailsPanelLayout);
        passengerDetailsPanelLayout.setHorizontalGroup(
            passengerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passengerDetailsPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(passengerDetails)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        passengerDetailsPanelLayout.setVerticalGroup(
            passengerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passengerDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passengerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel2.add(passengerDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 380, 80));

        flighDetailstPanel.setBackground(new java.awt.Color(255, 51, 51));
        flighDetailstPanel.setForeground(new java.awt.Color(255, 255, 255));
        flighDetailstPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flighDetailstPanelMouseClicked(evt);
            }
        });

        flightDetails.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        flightDetails.setForeground(new java.awt.Color(255, 255, 255));
        flightDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Flight_Icon.png"))); // NOI18N
        flightDetails.setText("  Flight Details");

        javax.swing.GroupLayout flighDetailstPanelLayout = new javax.swing.GroupLayout(flighDetailstPanel);
        flighDetailstPanel.setLayout(flighDetailstPanelLayout);
        flighDetailstPanelLayout.setHorizontalGroup(
            flighDetailstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flighDetailstPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(flightDetails)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        flighDetailstPanelLayout.setVerticalGroup(
            flighDetailstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flighDetailstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flightDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel2.add(flighDetailstPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 380, 80));

        ticketBookingPanel.setBackground(new java.awt.Color(51, 51, 51));
        ticketBookingPanel.setForeground(new java.awt.Color(255, 255, 255));
        ticketBookingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketBookingPanelMouseClicked(evt);
            }
        });

        ticketBooking.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        ticketBooking.setForeground(new java.awt.Color(255, 255, 255));
        ticketBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Ticket_Icon.png"))); // NOI18N
        ticketBooking.setText("  Ticket Booking");

        javax.swing.GroupLayout ticketBookingPanelLayout = new javax.swing.GroupLayout(ticketBookingPanel);
        ticketBookingPanel.setLayout(ticketBookingPanelLayout);
        ticketBookingPanelLayout.setHorizontalGroup(
            ticketBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketBookingPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(ticketBooking)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        ticketBookingPanelLayout.setVerticalGroup(
            ticketBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketBookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel2.add(ticketBookingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 380, 80));

        ticketCancellationPanel.setBackground(new java.awt.Color(51, 51, 51));
        ticketCancellationPanel.setForeground(new java.awt.Color(255, 255, 255));
        ticketCancellationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketCancellationPanelMouseClicked(evt);
            }
        });

        ticketCancellation.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        ticketCancellation.setForeground(new java.awt.Color(255, 255, 255));
        ticketCancellation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Cancel_Ticket_Icon.png"))); // NOI18N
        ticketCancellation.setText("  Ticket Cancellation");

        javax.swing.GroupLayout ticketCancellationPanelLayout = new javax.swing.GroupLayout(ticketCancellationPanel);
        ticketCancellationPanel.setLayout(ticketCancellationPanelLayout);
        ticketCancellationPanelLayout.setHorizontalGroup(
            ticketCancellationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketCancellationPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(ticketCancellation)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        ticketCancellationPanelLayout.setVerticalGroup(
            ticketCancellationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketCancellationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketCancellation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel2.add(ticketCancellationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 380, 80));

        LogoutPanel.setBackground(new java.awt.Color(51, 51, 51));
        LogoutPanel.setForeground(new java.awt.Color(255, 255, 255));
        LogoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Logout_Exit_Icon.png"))); // NOI18N
        logout.setText("  Logout");

        javax.swing.GroupLayout LogoutPanelLayout = new javax.swing.GroupLayout(LogoutPanel);
        LogoutPanel.setLayout(LogoutPanelLayout);
        LogoutPanelLayout.setHorizontalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(logout)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        LogoutPanelLayout.setVerticalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel2.add(LogoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 380, 80));

        sidebarIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Menu_Icon.png"))); // NOI18N
        SideBarPanel2.add(sidebarIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        getContentPane().add(SideBarPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 1080));

        setSize(new java.awt.Dimension(1920, 1080));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void Dashboard2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dashboard2MouseClicked
        // TODO add your handling code here:
        Admin_Dashboard obj = new Admin_Dashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Dashboard2MouseClicked

    private void passengerDetailsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passengerDetailsPanelMouseClicked
        // TODO add your handling code here:
        Admin_PassengerDetails obj = new Admin_PassengerDetails();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_passengerDetailsPanelMouseClicked

    private void flighDetailstPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flighDetailstPanelMouseClicked
        // TODO add your handling code here:
        Admin_FlightDetails obj = new Admin_FlightDetails();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_flighDetailstPanelMouseClicked

    private void ticketBookingPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketBookingPanelMouseClicked
        // TODO add your handling code here:
        Admin_TicketBookingDetails obj = new Admin_TicketBookingDetails();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ticketBookingPanelMouseClicked

    private void ticketCancellationPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketCancellationPanelMouseClicked
        // TODO add your handling code here:
        Admin_TicketCancellation obj = new Admin_TicketCancellation();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ticketCancellationPanelMouseClicked

    private void LogoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseClicked
        // TODO add your handling code here:
        LogIn obj = new LogIn();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutPanelMouseClicked

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        Admin_FlightDetails obj = new Admin_FlightDetails();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        DB_Connectivity db=new DB_Connectivity();

        ResultSet rs;
        rs=db.findFlight(searchField.getText());
        DefaultTableModel tb=(DefaultTableModel)flightDetailsTable.getModel();
        tb.setRowCount(0);
        try {
            while(rs.next()){
                String vector[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                tb.addRow(vector);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FlightTimings.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_searchButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        Admin_FlightAdd pa = new Admin_FlightAdd();
        pa.setVisible(true);
        dispose();
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
         DB_Connectivity db=new DB_Connectivity();
         DefaultTableModel tb=(DefaultTableModel)flightDetailsTable.getModel();
         String rowid=(String) tb.getValueAt(flightDetailsTable.getSelectedRow(),0);
        if(db.RemoveFlightBYID(rowid)==1){
        
            JOptionPane.showMessageDialog(this, "Removed","Alert",1);
        }else{
        
        
            JOptionPane.showMessageDialog(this, "Error","Alert",2);
        }
        
        
                try {
           
            
            rs=db.getFlightDetails();
          tb.setRowCount(0);
            while(rs.next()){
            String row[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
            tb.addRow(row);    
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(DB_Connectivity.class.getName()).log(Level.SEVERE, null, ex);
        }
                Admin_FlightDetails afd = new  Admin_FlightDetails();
                afd.setVisible(true);
                dispose();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        Admin_FlightUpdate fu = new Admin_FlightUpdate();
        fu.setVisible(true);
        dispose();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:
        DB_Connectivity db=new DB_Connectivity();

        ResultSet rs;
        rs=db.findFlight(searchField.getText());
        DefaultTableModel tb=(DefaultTableModel)flightDetailsTable.getModel();
       // tb.setRowCount(0);
        try {
            while(rs.next()){
                String vector[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                tb.addRow(vector);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FlightTimings.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_searchFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_FlightDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard2;
    private javax.swing.JPanel LogoutPanel;
    private javax.swing.JPanel SideBarPanel2;
    private javax.swing.JPanel TitleBarPanel;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel dashbaord;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel flighDetailstPanel;
    private javax.swing.JLabel flightDetails;
    private rojeru_san.complementos.RSTableMetro flightDetailsTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel passengerDetails;
    private javax.swing.JLabel passengerDetailsLabel;
    private javax.swing.JLabel passengerDetailsLabel1;
    private javax.swing.JPanel passengerDetailsPanel;
    private javax.swing.JLabel projectTitleLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel sidebarIconLabel;
    private javax.swing.JLabel ticketBooking;
    private javax.swing.JPanel ticketBookingPanel;
    private javax.swing.JLabel ticketCancellation;
    private javax.swing.JPanel ticketCancellationPanel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
