/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;
import users.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javaProject.DB_Connectivity;
import javaProject.LogIn;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class Admin_PassengerAdd extends javax.swing.JFrame {

    public Admin_PassengerAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBarPanel2 = new javax.swing.JPanel();
        Dashboard2 = new javax.swing.JPanel();
        dashbaord = new javax.swing.JLabel();
        passengerDetailsPanel = new javax.swing.JPanel();
        passengerDetails = new javax.swing.JLabel();
        flighDetailstPanel = new javax.swing.JPanel();
        flightDetails = new javax.swing.JLabel();
        ticketBookingPanel = new javax.swing.JPanel();
        ticketBooking = new javax.swing.JLabel();
        ticketCancellationPanel = new javax.swing.JPanel();
        ticketCancellation = new javax.swing.JLabel();
        LogoutPanel = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        sidebarIconLabel = new javax.swing.JLabel();
        TitleBarPanel = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        projectTitleLabel = new javax.swing.JLabel();
        adminLabel = new javax.swing.JLabel();
        dashboardPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passportTextField = new javax.swing.JTextField();
        contactLabel = new javax.swing.JLabel();
        contactTextField = new javax.swing.JTextField();
        resetEverythingButton = new javax.swing.JButton();
        addressTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        cnicTextField = new javax.swing.JTextField();
        ticketbookinglabel = new javax.swing.JLabel();
        ticketbookingicon = new javax.swing.JLabel();
        cnicLabel = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        passengerid = new javax.swing.JLabel();
        passenger = new javax.swing.JTextField();
        pidlabel = new javax.swing.JLabel();
        contactValidation = new javax.swing.JLabel();
        passportValidation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideBarPanel2.setBackground(new java.awt.Color(51, 51, 51));
        SideBarPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard2.setBackground(new java.awt.Color(51, 51, 51));
        Dashboard2.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dashboard2MouseClicked(evt);
            }
        });

        dashbaord.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        dashbaord.setForeground(new java.awt.Color(255, 255, 255));
        dashbaord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Home_Icon.png"))); // NOI18N
        dashbaord.setText("  Dashboard");

        javax.swing.GroupLayout Dashboard2Layout = new javax.swing.GroupLayout(Dashboard2);
        Dashboard2.setLayout(Dashboard2Layout);
        Dashboard2Layout.setHorizontalGroup(
            Dashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dashboard2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(dashbaord)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        Dashboard2Layout.setVerticalGroup(
            Dashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dashboard2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashbaord, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel2.add(Dashboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 380, 80));

        passengerDetailsPanel.setBackground(new java.awt.Color(255, 51, 51));
        passengerDetailsPanel.setForeground(new java.awt.Color(255, 255, 255));
        passengerDetailsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passengerDetailsPanelMouseClicked(evt);
            }
        });

        passengerDetails.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        passengerDetails.setForeground(new java.awt.Color(255, 255, 255));
        passengerDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Passenger_Icon.png"))); // NOI18N
        passengerDetails.setText("  Passenger Details");

        javax.swing.GroupLayout passengerDetailsPanelLayout = new javax.swing.GroupLayout(passengerDetailsPanel);
        passengerDetailsPanel.setLayout(passengerDetailsPanelLayout);
        passengerDetailsPanelLayout.setHorizontalGroup(
            passengerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passengerDetailsPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(passengerDetails)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        passengerDetailsPanelLayout.setVerticalGroup(
            passengerDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passengerDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passengerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel2.add(passengerDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 380, 80));

        flighDetailstPanel.setBackground(new java.awt.Color(51, 51, 51));
        flighDetailstPanel.setForeground(new java.awt.Color(255, 255, 255));
        flighDetailstPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flighDetailstPanelMouseClicked(evt);
            }
        });

        flightDetails.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        flightDetails.setForeground(new java.awt.Color(255, 255, 255));
        flightDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Flight_Icon.png"))); // NOI18N
        flightDetails.setText("  Flight Details");

        javax.swing.GroupLayout flighDetailstPanelLayout = new javax.swing.GroupLayout(flighDetailstPanel);
        flighDetailstPanel.setLayout(flighDetailstPanelLayout);
        flighDetailstPanelLayout.setHorizontalGroup(
            flighDetailstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flighDetailstPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(flightDetails)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        flighDetailstPanelLayout.setVerticalGroup(
            flighDetailstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flighDetailstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flightDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel2.add(flighDetailstPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 380, 80));

        ticketBookingPanel.setBackground(new java.awt.Color(51, 51, 51));
        ticketBookingPanel.setForeground(new java.awt.Color(255, 255, 255));
        ticketBookingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketBookingPanelMouseClicked(evt);
            }
        });

        ticketBooking.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        ticketBooking.setForeground(new java.awt.Color(255, 255, 255));
        ticketBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Ticket_Icon.png"))); // NOI18N
        ticketBooking.setText("  Ticket Booking");

        javax.swing.GroupLayout ticketBookingPanelLayout = new javax.swing.GroupLayout(ticketBookingPanel);
        ticketBookingPanel.setLayout(ticketBookingPanelLayout);
        ticketBookingPanelLayout.setHorizontalGroup(
            ticketBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketBookingPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(ticketBooking)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        ticketBookingPanelLayout.setVerticalGroup(
            ticketBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketBookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel2.add(ticketBookingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 380, 80));

        ticketCancellationPanel.setBackground(new java.awt.Color(51, 51, 51));
        ticketCancellationPanel.setForeground(new java.awt.Color(255, 255, 255));
        ticketCancellationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketCancellationPanelMouseClicked(evt);
            }
        });

        ticketCancellation.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        ticketCancellation.setForeground(new java.awt.Color(255, 255, 255));
        ticketCancellation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Cancel_Ticket_Icon.png"))); // NOI18N
        ticketCancellation.setText("  Ticket Cancellation");

        javax.swing.GroupLayout ticketCancellationPanelLayout = new javax.swing.GroupLayout(ticketCancellationPanel);
        ticketCancellationPanel.setLayout(ticketCancellationPanelLayout);
        ticketCancellationPanelLayout.setHorizontalGroup(
            ticketCancellationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketCancellationPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(ticketCancellation)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        ticketCancellationPanelLayout.setVerticalGroup(
            ticketCancellationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketCancellationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketCancellation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel2.add(ticketCancellationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 380, 80));

        LogoutPanel.setBackground(new java.awt.Color(51, 51, 51));
        LogoutPanel.setForeground(new java.awt.Color(255, 255, 255));
        LogoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Segoe UI Semilight", 1, 19)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Logout_Exit_Icon.png"))); // NOI18N
        logout.setText("  Logout");

        javax.swing.GroupLayout LogoutPanelLayout = new javax.swing.GroupLayout(LogoutPanel);
        LogoutPanel.setLayout(LogoutPanelLayout);
        LogoutPanelLayout.setHorizontalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(logout)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        LogoutPanelLayout.setVerticalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideBarPanel2.add(LogoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 380, 80));

        sidebarIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Menu_Icon.png"))); // NOI18N
        SideBarPanel2.add(sidebarIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        getContentPane().add(SideBarPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 1080));

        TitleBarPanel.setBackground(new java.awt.Color(102, 102, 255));
        TitleBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setBackground(new java.awt.Color(255, 255, 255));
        closeLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 28)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLabel.setText("X");
        closeLabel.setToolTipText("");
        closeLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        TitleBarPanel.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 20, 50, 50));

        projectTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        projectTitleLabel.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        projectTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        projectTitleLabel.setText("AIRLINE TICKET BOOKING SYSTEM");
        TitleBarPanel.add(projectTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 15, 970, -1));

        adminLabel.setBackground(new java.awt.Color(255, 255, 255));
        adminLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        adminLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/User_Icon.png"))); // NOI18N
        adminLabel.setText(" Admin");
        TitleBarPanel.add(adminLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 20, -1, -1));

        getContentPane().add(TitleBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 1540, 90));

        dashboardPanel.setBackground(new java.awt.Color(255, 255, 255));

        nameLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(51, 51, 51));
        nameLabel.setText("Name :");

        nameTextField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N

        passwordLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(51, 51, 51));
        passwordLabel.setText("Passport :");

        passportTextField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N

        contactLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        contactLabel.setForeground(new java.awt.Color(51, 51, 51));
        contactLabel.setText("Contact :");

        contactTextField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        contactTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactTextFieldKeyReleased(evt);
            }
        });

        resetEverythingButton.setBackground(new java.awt.Color(51, 51, 51));
        resetEverythingButton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        resetEverythingButton.setForeground(new java.awt.Color(255, 255, 255));
        resetEverythingButton.setText("Reset");
        resetEverythingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetEverythingButtonActionPerformed(evt);
            }
        });

        addressTextField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N

        addressLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(51, 51, 51));
        addressLabel.setText("Address : ");

        genderLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(51, 51, 51));
        genderLabel.setText("Gender :");

        cnicTextField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N

        ticketbookinglabel.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        ticketbookinglabel.setForeground(new java.awt.Color(255, 51, 51));
        ticketbookinglabel.setText("PASSENGER INFORMATION");

        ticketbookingicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Passenger_Img.png"))); // NOI18N

        cnicLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        cnicLabel.setForeground(new java.awt.Color(51, 51, 51));
        cnicLabel.setText("CNIC :");

        genderComboBox.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Gender", "Male", "Female" }));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });

        submitButton.setBackground(new java.awt.Color(51, 51, 51));
        submitButton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        passengerid.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 28)); // NOI18N
        passengerid.setForeground(new java.awt.Color(51, 51, 255));

        passenger.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        passenger.setText("PSG-");

        pidlabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        pidlabel.setForeground(new java.awt.Color(51, 51, 51));
        pidlabel.setText("P_ID :");

        passportValidation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passportValidationKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ticketbookingicon, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ticketbookinglabel)
                .addGap(300, 300, 300))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addContainerGap(110, Short.MAX_VALUE)
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLabel)
                            .addComponent(passengerid)
                            .addComponent(genderLabel)
                            .addComponent(cnicLabel)
                            .addComponent(pidlabel))
                        .addGap(22, 22, 22)
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cnicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passenger, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                                    .addComponent(contactLabel)
                                    .addGap(18, 18, 18)
                                    .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(contactValidation)
                                        .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(3, 3, 3))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                                    .addComponent(passwordLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(passportValidation)
                                        .addComponent(passportTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 155, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                        .addComponent(resetEverythingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ticketbookingicon)
                    .addComponent(ticketbookinglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(passengerid)
                .addGap(86, 86, 86)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passenger, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pidlabel)
                            .addComponent(nameLabel)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLabel)
                            .addComponent(cnicLabel)
                            .addComponent(cnicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(passportTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(passportValidation)
                .addGap(72, 72, 72)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactLabel)
                    .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(contactValidation)
                .addGap(73, 73, 73)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(80, 80, 80)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(resetEverythingButton))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        getContentPane().add(dashboardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 1540, 990));

        setSize(new java.awt.Dimension(1920, 1080));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void resetEverythingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetEverythingButtonActionPerformed
        // TODO add your handling code here:
        nameTextField.setText(null);
        cnicTextField.setText(null);
        passportTextField.setText(null);
        genderComboBox.setSelectedIndex(0);
        contactTextField.setText(null);
        addressTextField.setText(null);
    }//GEN-LAST:event_resetEverythingButtonActionPerformed

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        String name = nameTextField.getText();
        String pid = passenger.getText();
        String cnic = cnicTextField.getText();
        String passport = passportTextField.getText();
        String contact = contactTextField.getText();
        String address = addressTextField.getText();
        
        
        String namePattern = "^[a-zA-Z]{4,}(?: [a-zA-Z]+){0,2}$";
        String pidPattern = "^PSG-\\d{3}$";
        String cnicPattern = "^[0-9+]{5}-[0-9+]{7}-[0-9]{1}$";
        String passportPattern = "^(?!^0+$)[a-zA-Z0-9]{6,20}$";
        String contactPattern = "^(03)[0-9]{9}$";
        String addressPattern = "^[A-Za-z0-9 ,\\-]+$";
        
        if (!name.matches(namePattern)) {
        JOptionPane.showMessageDialog(this, "Invalid name");
    } else if (!pid.matches(pidPattern)) {
        JOptionPane.showMessageDialog(this, "Use this format: PSG-XXX", "Invalid Passenger ID",2);
    } else if (!cnic.matches(cnicPattern)) {
        JOptionPane.showMessageDialog(this, "Use this format: XXXXX-XXXXXXX-X", "Invalid CNIC", 2);
    } else if (!passport.matches(passportPattern)) {
        JOptionPane.showMessageDialog(this, "Atleast 6-20 Characters and Numbers", "Invalid passport number",2);
    } else if (!contact.matches(contactPattern)) {
       JOptionPane.showMessageDialog(this, "Use this format: 03XXXXXXXXX", "Invalid Phone Number", 2);
    } else if (!address.matches(addressPattern)) {
        JOptionPane.showMessageDialog(this, "Invalid address");
    } else {
        // All input is valid, proceed with further actions
    
        
        DB_Connectivity db = new DB_Connectivity();
        if(db.GetPassengerDetails(passenger.getText(), nameTextField.getText(), cnicTextField.getText(), passportTextField.getText(), genderComboBox.getSelectedItem().toString(), contactTextField.getText(), addressTextField.getText())==1){
            JOptionPane.showMessageDialog(this, "Successfully Passenger Details has been added", "Passenger Details", 1);
        }else{
            JOptionPane.showMessageDialog(this, "Unsuccessful! Please complete Passenger Details", "Passenger Details", 2);
        }
        Admin_PassengerDetails ps = new Admin_PassengerDetails();
        ps.setVisible(true);
        dispose();
    }//GEN-LAST:event_submitButtonActionPerformed
    }
    private void contactTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactTextFieldKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_contactTextFieldKeyReleased

    private void passportValidationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passportValidationKeyReleased
        // TODO add your handling code here
    }//GEN-LAST:event_passportValidationKeyReleased

    private void LogoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseClicked
        // TODO add your handling code here:
        LogIn obj = new LogIn();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutPanelMouseClicked

    private void ticketCancellationPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketCancellationPanelMouseClicked
        // TODO add your handling code here:
        Admin_TicketCancellation obj = new Admin_TicketCancellation();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ticketCancellationPanelMouseClicked

    private void ticketBookingPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketBookingPanelMouseClicked
        // TODO add your handling code here:
        Admin_TicketBookingDetails obj = new Admin_TicketBookingDetails();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ticketBookingPanelMouseClicked

    private void flighDetailstPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flighDetailstPanelMouseClicked
        // TODO add your handling code here:
        Admin_FlightDetails obj = new Admin_FlightDetails();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_flighDetailstPanelMouseClicked

    private void passengerDetailsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passengerDetailsPanelMouseClicked
        // TODO add your handling code here:
        Admin_PassengerDetails obj = new Admin_PassengerDetails();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_passengerDetailsPanelMouseClicked

    private void Dashboard2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dashboard2MouseClicked
        // TODO add your handling code here:
        Admin_Dashboard obj = new Admin_Dashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_Dashboard2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_PassengerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_PassengerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_PassengerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_PassengerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_PassengerAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard2;
    private javax.swing.JPanel LogoutPanel;
    private javax.swing.JPanel SideBarPanel2;
    private javax.swing.JPanel TitleBarPanel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel cnicLabel;
    private javax.swing.JTextField cnicTextField;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JLabel contactValidation;
    private javax.swing.JLabel dashbaord;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel flighDetailstPanel;
    private javax.swing.JLabel flightDetails;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField passenger;
    private javax.swing.JLabel passengerDetails;
    private javax.swing.JPanel passengerDetailsPanel;
    private javax.swing.JLabel passengerid;
    private javax.swing.JTextField passportTextField;
    private javax.swing.JLabel passportValidation;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel pidlabel;
    private javax.swing.JLabel projectTitleLabel;
    private javax.swing.JButton resetEverythingButton;
    private javax.swing.JLabel sidebarIconLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel ticketBooking;
    private javax.swing.JPanel ticketBookingPanel;
    private javax.swing.JLabel ticketCancellation;
    private javax.swing.JPanel ticketCancellationPanel;
    private javax.swing.JLabel ticketbookingicon;
    private javax.swing.JLabel ticketbookinglabel;
    // End of variables declaration//GEN-END:variables
}
